spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbtraining?useSSL=false&serverTimezone=UTC
    username: root
    password:
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: gb.sample.model
