spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gbtraining
    username: postgres
    password: persol
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: gb.sample.model
